In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4])

In [3]:
print(arr_1d)

[1 2 3 4]


In [4]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
arr_1d.ndim                  # to know the DIMENTION of the array

1

In [6]:
arr_2d.ndim                  # to know the DIMENTION of the array

2

In [7]:
arr_1d.shape                 # to know the SHAPE of the array

(4,)

In [8]:
arr_2d.shape                 # to know the SHAPE of the array      # will represent in (row, coloum)

(2, 4)

In [9]:
arr_1d.size                  # to know the SIZE OR ELEMENT of the array

4

In [10]:
arr_2d.size                  # to know the SIZE OR ELEMENT of the array

8

In [11]:
arr_1d.dtype                 # to know the DTATYPE of the array

dtype('int32')

In [12]:
arr_2d.dtype                 # to know the DTATYPE of the array

dtype('int32')

In [13]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr_1da = np.array([1,2,3,4,'abc',np.nan,np.NAN])
print(arr_1da)

['1' '2' '3' '4' 'abc' 'nan' 'nan']
