#              Con-cat-enate : concatenate()

In [1]:
import numpy as np

In [2]:
arr_1 = np.arange(0,20).reshape(5,4)
print(arr_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [3]:
arr_2 = np.arange(20,40).reshape(5,4)
print(arr_2)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [4]:
arr_3 = np.concatenate((arr_1,arr_2))                        # join two array
print(arr_3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [5]:
arr_4 = np.concatenate((arr_1,arr_2)).reshape(4,10)     # its modifie array while reshaping
print(arr_4)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [6]:
arr_5 = np.concatenate((arr_1,arr_2), axis=0)            # join array as per colom to colom
print(arr_5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [7]:
arr_6 = np.vstack((arr_1,arr_2))                  # join array (as per colom to colom) VERTICALLY
print(arr_6)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [8]:
arr_7 = np.concatenate((arr_1,arr_2), axis=1)           # join array as per row to row
print(arr_7)

[[ 0  1  2  3 20 21 22 23]
 [ 4  5  6  7 24 25 26 27]
 [ 8  9 10 11 28 29 30 31]
 [12 13 14 15 32 33 34 35]
 [16 17 18 19 36 37 38 39]]


In [9]:
arr_8 = np.hstack((arr_1,arr_2))                        # join array (as per row to row) HORIZONTALLY
print(arr_8)
arr_8.dtype

[[ 0  1  2  3 20 21 22 23]
 [ 4  5  6  7 24 25 26 27]
 [ 8  9 10 11 28 29 30 31]
 [12 13 14 15 32 33 34 35]
 [16 17 18 19 36 37 38 39]]


dtype('int32')

#                SPLIT  : split()

In [10]:
arr_9 = np.arange(0,16).reshape(4,4)#.split(arr_9,2)                
print(arr_9) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [11]:
arr_9a = np.split(arr_9,2)         # it gives result always in LIST formate # do not use dtype in list   
print(arr_9a) 
type(arr_9a)
#arr_9a.dtype      ERROR #     'list' object has no attribute 'dtype'

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


list

In [12]:
arr_9a = np.split(arr_9,2, axis=1)
print(arr_9a)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [13]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10])#.split(arr_1d,[2,6])
print(arr_1d)
np.split(arr_1d,[2,6])
                      
    #   or else
    

[ 1  2  3  4  5  6  7  8  9 10]


[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10])]

In [14]:
arr_1da = np.split(arr_1d,[2,6])
print(arr_1da)

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10])]


#               chk other posiblities

In [15]:
arr_9x = np.split(arr_1,(2,3))
print(arr_9x)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19]])]


In [16]:
arr_9y = np.split(arr_1,(4,1))
print(arr_9y)

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([], shape=(0, 4), dtype=int32), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])]


In [17]:
arr_9z = np.split(arr_1,(3,2))
print(arr_9z)

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([], shape=(0, 4), dtype=int32), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])]
