# Numpy_functions

In [5]:
import numpy as np

# Arange :  arange()

In [2]:
arr1_1d = np.arange(1,15)                        # define range between two values
print(arr1_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
arr2_1d = np.arange(20)                         # it consider from 0 for not given value
print(arr2_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
arr3_1d = np.arange(20,2)                        # it won't understand this type of value
print(arr3_1d)

[]


In [5]:
arr4_1d = np.arange(0,20,2)                      # define range between first two value in difference of given third value 
print(arr4_1d)

[ 0  2  4  6  8 10 12 14 16 18]


In [6]:
arr4a_1d = np.arange(0,20,5)                      # define range between first two value in difference of given third value 
print(arr4a_1d)

[ 0  5 10 15]


# LinSpace : linspace()

In [7]:
arr5_1d = np.linspace(1,20,2)                   # devide first two values in similar spam of third value
print(arr5_1d)                                        # check more expl below

[ 1. 20.]


In [8]:
arr5_1d.dtype

dtype('float64')

In [9]:
arr5aa_1d = np.linspace(1,20,5) #,dtype = int)     # try to change its data-type but its giving error
print(arr5aa_1d) 

[ 1.    5.75 10.5  15.25 20.  ]


In [10]:
arr5a_1d = np.linspace(1,20,5)                 # devide first two values in similar spam of third value
print(arr5a_1d)#.dtype
arr5a_1d.dtype

[ 1.    5.75 10.5  15.25 20.  ]


dtype('float64')

In [11]:
arr5b_1d = np.linspace(1,20,10)                   # devide first two values in similar spam of third value
print(arr5b_1d)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [3]:
arr5c_1d = np.linspace(1,20,18 , endpoint = False)                   # devide first two values in similar spam of third value
print(arr5c_1d)

[ 1.          2.05555556  3.11111111  4.16666667  5.22222222  6.27777778
  7.33333333  8.38888889  9.44444444 10.5        11.55555556 12.61111111
 13.66666667 14.72222222 15.77777778 16.83333333 17.88888889 18.94444444]


# Reshape  : reshape()

In [13]:
arr6_2d = arr5c_1d.reshape(6,3)                   # give shape as difine in (row, colom)
print(arr6_2d)

[[ 1.          2.11764706  3.23529412]
 [ 4.35294118  5.47058824  6.58823529]
 [ 7.70588235  8.82352941  9.94117647]
 [11.05882353 12.17647059 13.29411765]
 [14.41176471 15.52941176 16.64705882]
 [17.76470588 18.88235294 20.        ]]


In [7]:
arr6a_2d = np.reshape(arr5c_1d , (6,3))                   # give shape as difine in (row, colom)
print(arr6a_2d)

[[ 1.          2.05555556  3.11111111]
 [ 4.16666667  5.22222222  6.27777778]
 [ 7.33333333  8.38888889  9.44444444]
 [10.5        11.55555556 12.61111111]
 [13.66666667 14.72222222 15.77777778]
 [16.83333333 17.88888889 18.94444444]]


In [8]:
arr6b_2d = np.reshape(arr5c_1d , (3,6))                   # give shape as difine in (row, colom)
print(arr6b_2d)

[[ 1.          2.05555556  3.11111111  4.16666667  5.22222222  6.27777778]
 [ 7.33333333  8.38888889  9.44444444 10.5        11.55555556 12.61111111]
 [13.66666667 14.72222222 15.77777778 16.83333333 17.88888889 18.94444444]]


#  Using both in one stmt :    Linspace and Reshape 

In [14]:
arr7_2d = np.linspace(1,20,18).reshape(6,3)
print(arr7_2d)

[[ 1.          2.11764706  3.23529412]
 [ 4.35294118  5.47058824  6.58823529]
 [ 7.70588235  8.82352941  9.94117647]
 [11.05882353 12.17647059 13.29411765]
 [14.41176471 15.52941176 16.64705882]
 [17.76470588 18.88235294 20.        ]]


In [15]:
arr8_3d = np.linspace(1,20,18).reshape(2,3,3)
print(arr8_3d)

[[[ 1.          2.11764706  3.23529412]
  [ 4.35294118  5.47058824  6.58823529]
  [ 7.70588235  8.82352941  9.94117647]]

 [[11.05882353 12.17647059 13.29411765]
  [14.41176471 15.52941176 16.64705882]
  [17.76470588 18.88235294 20.        ]]]


#           Using Arange and Reshape 

In [16]:
arr9_1d = np.arange(1,15).reshape(7,2)
print(arr9_1d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


#  Ravel   : ravel()

In [17]:
arr10_1d = arr9_1d.ravel()                            # decrease dimension  from "2d " to "1d"
print(arr10_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
arr10a_1d = arr8_3d.ravel()                          # decrease dimension   from "3d" to "2d"
print(arr10a_1d)

[ 1.          2.11764706  3.23529412  4.35294118  5.47058824  6.58823529
  7.70588235  8.82352941  9.94117647 11.05882353 12.17647059 13.29411765
 14.41176471 15.52941176 16.64705882 17.76470588 18.88235294 20.        ]


In [19]:
arr10b_1d = np.arange(1,15).ravel()                     # not change from 1d
print(arr10b_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Flattten :  flatten()

In [20]:
arr11_1d = arr9_1d.flatten()                            # decrease dimension  from "2d " to "1d"
print(arr11_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
arr11a_1d = arr8_3d.flatten()                            # decrease dimension   from "3d" to "2d"
print(arr11a_1d)

[ 1.          2.11764706  3.23529412  4.35294118  5.47058824  6.58823529
  7.70588235  8.82352941  9.94117647 11.05882353 12.17647059 13.29411765
 14.41176471 15.52941176 16.64705882 17.76470588 18.88235294 20.        ]


In [22]:
arr11b_1d = arr4a_1d.flatten()                             # not change from 1d
print(arr11b_1d)

[ 0  5 10 15]


# Transpose  : transpose()

In [23]:
arr12_1d = arr4a_1d.transpose()                     #Interchange ROWs and COLOMs positions
print(arr12_1d)

[ 0  5 10 15]


In [24]:
arr12_2d = arr9_1d.transpose()                       #Interchange ROWs and COLOMs positions
print(arr12_2d)

[[ 1  3  5  7  9 11 13]
 [ 2  4  6  8 10 12 14]]


In [25]:
arr12_3d = arr8_3d.transpose()                       #Interchange ROWs and COLOMs positions
print(arr12_3d)

[[[ 1.         11.05882353]
  [ 4.35294118 14.41176471]
  [ 7.70588235 17.76470588]]

 [[ 2.11764706 12.17647059]
  [ 5.47058824 15.52941176]
  [ 8.82352941 18.88235294]]

 [[ 3.23529412 13.29411765]
  [ 6.58823529 16.64705882]
  [ 9.94117647 20.        ]]]


In [26]:
arr12a_3d = arr8_3d.T                              #Interchange ROWs and COLOMs positions
print(arr12a_3d)                                         #can use only T

[[[ 1.         11.05882353]
  [ 4.35294118 14.41176471]
  [ 7.70588235 17.76470588]]

 [[ 2.11764706 12.17647059]
  [ 5.47058824 15.52941176]
  [ 8.82352941 18.88235294]]

 [[ 3.23529412 13.29411765]
  [ 6.58823529 16.64705882]
  [ 9.94117647 20.        ]]]


# slicing  :  slicing[]

In [ ]:
         #matx_20[0:no.,lastno.:last_no]

In [39]:
matx_20 = np.arange(0,40,2).reshape(5,4)
print(matx_20)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]]


In [40]:
matx_20 = np.arange(0,40,2).reshape(5,4)
print(matx_20[0:3,2:5])

[[ 4  6]
 [12 14]
 [20 22]]


In [31]:
max_100 = np.arange(1,101)
print(max_100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [32]:
max_100a = np.arange(1,101).reshape(10,10)
print(max_100a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [34]:
max_100b = np.arange(1,101).reshape(10,10)#.max_100b[2:4,2:4]
print(max_100b[2:4,2:4])

[[23 24]
 [33 34]]
