In [2]:
import numpy as np

In [2]:
#import matplotlib as plt

In [3]:
#import pandas as pd

In [4]:
import random as rd

In [3]:
x1 = np.random.random((3,3))
x1

array([[0.29830339, 0.52090774, 0.77409571],
       [0.22600157, 0.34411651, 0.10205658],
       [0.26093318, 0.38527517, 0.10418096]])

In [5]:
x2 = np.random.randint(4,15 , (3,2))
x2

array([[12,  7],
       [ 9, 14],
       [13,  5]])

In [5]:
from numpy import random                           #maximum 6 elemets can come in one time result

x = random.binomial(n=10, p=0.1, size=10)          # p = probability , p<1 and p>0  
                                                                      #  0<p<1  
print(x)                                                              #  0.1<P<1

[0 0 2 0 0 1 1 1 0 1]


In [6]:
from numpy import random                           #maximum 10 elemets can come in one time result

x = random.binomial(n=10, p=1, size=10)            # that means all time only 10 will come

print(x)

[10 10 10 10 10 10 10 10 10 10]
