In [1]:
# matrix tutorial

In [7]:
import numpy as np

In [3]:
matx_1 = np.array([[1,1,1],[1,1,1]])
print(matx_1)

[[1 1 1]
 [1 1 1]]


In [4]:
matx_1.dtype

dtype('int32')

In [5]:
matx_1.ndim

2

In [6]:
matx_1.shape

(2, 3)

In [7]:
matx_1.size

6

In [8]:
matx_2 = np.array(5)
print(matx_2)

5


In [2]:
matx_f = np.full((4,3), 5)
print(matx_f)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [6]:
matx_i = np.eye(5)                  # identiti matrix
print(matx_i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
matx_d = np.diag([10,20,30,40,50])
print(matx_d)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [9]:
matx_3 = np.ones(5)
print(matx_3)

[1. 1. 1. 1. 1.]


In [5]:
matx_3a = np.ones((4,3))
print(matx_3a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
matx_4 = np.ones((5), dtype = int)
print(matx_4)

[1 1 1 1 1]


In [11]:
matx_5 = np.ones((5,5), dtype = int)
print(matx_5)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
matx_6 = np.ones ((5,5), dtype = bool)
print(matx_6)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [13]:
matx_7 = np.zeros(5)
print(matx_7)

[0. 0. 0. 0. 0.]


In [14]:
matx_8 = np.zeros((5,5), dtype = int)
print(matx_8)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [15]:
matx_9 = np.zeros((5,5), dtype= bool)
print(matx_9)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [16]:
matx_9a = np.zeros((5,5), dtype= str)
print(matx_9a)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [17]:
em_str = ''
print(bool(em_str))

False


In [18]:
matx_9b = np.ones((5,5), dtype= str)
print(matx_9a)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [19]:
em_str = ''                                    # empty string always zero/false
print(bool(em_str))

False


In [20]:
matx_9c = np.empty((5,5))           # empty command never show empty matrix , it takes RANDOM value from available data 
print(matx_9c)

[[6.23042070e-307 4.22795269e-307 2.04722549e-306 6.23054972e-307
  1.06811422e-306]
 [3.56043054e-307 1.37961641e-306 8.90071135e-308 8.01097889e-307
  1.78020169e-306]
 [7.56601165e-307 1.02359984e-306 1.33510679e-306 2.22522597e-306
  1.33511018e-306]
 [6.23057689e-307 9.45754852e-308 1.27946076e-307 1.05700515e-307
  2.04712906e-306]
 [7.56589622e-307 1.11258277e-307 8.90111708e-307 3.17493010e-310
  9.38666179e+093]]


In [21]:
matx_100 = np.ones((100,100), dtype = int)
print(matx_100)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [22]:
matx_10 = np.ones((10,10), dtype = int)
print(matx_10)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [23]:
matx_10a = np.ones((10,10), dtype = int).reshape(20,5)
print(matx_10a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
